name: Hourly Job Alert

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  job-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Write credentials.json from secret
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job scraper
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python job_scraper.py
